
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNDynamicIconChangeSpec.h"

namespace facebook::react {



static facebook::jsi::Value __hostFunction_NativeDynamicIconChangeSpecJSI_changeAppIcon(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "changeAppIcon", "(Ljava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeDynamicIconChangeSpecJSI_getAppIcon(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getAppIcon", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeDynamicIconChangeSpecJSI::NativeDynamicIconChangeSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["changeAppIcon"] = MethodMetadata {1, __hostFunction_NativeDynamicIconChangeSpecJSI_changeAppIcon};
  methodMap_["getAppIcon"] = MethodMetadata {0, __hostFunction_NativeDynamicIconChangeSpecJSI_getAppIcon};
}

std::shared_ptr<TurboModule> RNDynamicIconChangeSpec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "DynamicIconChange") {
    return std::make_shared<NativeDynamicIconChangeSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
