/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "RNDynamicIconChangeSpec.h"


@implementation NativeDynamicIconChangeSpecBase


- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper
{
  _eventEmitterCallback = std::move(eventEmitterCallbackWrapper->_eventEmitterCallback);
}
@end


namespace facebook::react {
  
    static facebook::jsi::Value __hostFunction_NativeDynamicIconChangeSpecJSI_changeAppIcon(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "changeAppIcon", @selector(changeAppIcon:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeDynamicIconChangeSpecJSI_getAppIcon(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getAppIcon", @selector(getAppIcon:reject:), args, count);
    }

  NativeDynamicIconChangeSpecJSI::NativeDynamicIconChangeSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {
      
        methodMap_["changeAppIcon"] = MethodMetadata {1, __hostFunction_NativeDynamicIconChangeSpecJSI_changeAppIcon};
        
        
        methodMap_["getAppIcon"] = MethodMetadata {0, __hostFunction_NativeDynamicIconChangeSpecJSI_getAppIcon};
        
  }
} // namespace facebook::react
