/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNDynamicIconChangeSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeDynamicIconChangeCxxSpecJSI_getConstants(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDynamicIconChangeCxxSpecJSI *>(&turboModule)->getConstants(
    rt
  );
}
static jsi::Value __hostFunction_NativeDynamicIconChangeCxxSpecJSI_changeAppIcon(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDynamicIconChangeCxxSpecJSI *>(&turboModule)->changeAppIcon(
    rt,
    count <= 0 || args[0].isUndefined() ? std::nullopt : std::make_optional(args[0].asString(rt))
  );
}
static jsi::Value __hostFunction_NativeDynamicIconChangeCxxSpecJSI_getAppIcon(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDynamicIconChangeCxxSpecJSI *>(&turboModule)->getAppIcon(
    rt
  );
}

NativeDynamicIconChangeCxxSpecJSI::NativeDynamicIconChangeCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("DynamicIconChange", jsInvoker) {
  methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_NativeDynamicIconChangeCxxSpecJSI_getConstants};
  methodMap_["changeAppIcon"] = MethodMetadata {1, __hostFunction_NativeDynamicIconChangeCxxSpecJSI_changeAppIcon};
  methodMap_["getAppIcon"] = MethodMetadata {0, __hostFunction_NativeDynamicIconChangeCxxSpecJSI_getAppIcon};
}


} // namespace facebook::react
